### ISSUE TITLE
I don't understand HTML <tags>

### ISSUE THREAD

**Issue by michaelmusick** [Montana-Media-Arts/341-work#4]
Can someone help me better understand, what an HTML tag is? Specifically, I am confused about the difference between tags and elements.

**Comment by michaelmusick** [comment]
Hey I am not totally sure, but, I believe a tag is used to define an element within an HTML document. 

@NickMolesUM, do you have more info about this you could provide? I remember talking with you about this earlier this week.

**Comment by ghost** [comment]
Hey Mikael, I wasn't sure if this was tagging me in something on github or not, and couldn't find it. Sorry for the late response, I was at my desk working all day yesterday just kinda ignoring my phone. I think that's an ok way to define an HTML tag, the only thing I could think of is to maybe elaborate on it, because the tag defines the element, but not everyone is going to understand what the element does, like the <h#> tag defines a title, but the # defines how large it is, and the <p> element is where the majority of text will be. That's my only thought on it though. Also, I will make that youtube video sometime today. 

 

 

Nick Moles

 

 

-----Original Message-----
